import type { EntityId } from "@game/core";
import type { CurrencyService } from "../currency/currency-service.js";
import type { WalletId } from "../currency/types.js";
import type { InventoryManager } from "../inventory/inventory-manager.js";
import { getEnchantmentLevel, type EnchantmentLevel, type ItemInstanceId } from "../inventory/types.js";
import { getNextEnchantmentRecipe, scaleEnchantmentRecipe, type EnchantmentCostCategory, type EnchantmentMaterialCost, type EnchantmentRecipe } from "./enchantment-recipes.js";

export interface EnchantmentItemInfo { readonly enchantable:boolean; readonly maximumLevel:EnchantmentLevel; readonly itemTier:number; readonly costCategory:EnchantmentCostCategory; readonly craftMaterials:readonly EnchantmentMaterialCost[]; }
export type EnchantmentItemInfoResolver=(itemId:string)=>EnchantmentItemInfo|undefined;
export type EnchantmentFailureReason="item_not_found"|"item_not_enchantable"|"maximum_level_reached"|"level_reserved"|"inventory_full"|"insufficient_silver"|"insufficient_materials"|"combat_active"|"transaction_already_processed";
export type EnchantmentResult={readonly ok:true;readonly instanceId:ItemInstanceId;readonly fromLevel:EnchantmentLevel;readonly toLevel:EnchantmentLevel}|{readonly ok:false;readonly reason:EnchantmentFailureReason};
export interface EnchantmentPreview { readonly instanceId:ItemInstanceId;readonly itemId:string;readonly currentLevel:EnchantmentLevel;readonly nextLevel:EnchantmentLevel|undefined;readonly enabled:boolean;readonly silverCost:number;readonly materials:readonly (EnchantmentMaterialCost&{readonly owned:number;readonly missing:number})[];readonly canAfford:boolean;readonly failureReason?:EnchantmentFailureReason; }
export interface EnchantmentServiceOptions { readonly inventoryManager:InventoryManager;readonly currencyService:CurrencyService;readonly walletId:WalletId;readonly inventoryOwnerId:EntityId;readonly resolveMaterialOwnerId?:(itemId:string)=>EntityId;readonly resolveItemInfo:EnchantmentItemInfoResolver;readonly canEnchantNow?:()=>boolean;readonly findEquippedEntry:(instanceId:ItemInstanceId)=>{readonly itemId:string;readonly instanceId:ItemInstanceId;readonly quantity:number;readonly enchantment?:EnchantmentLevel}|undefined;readonly changeEquippedEnchantment:(instanceId:ItemInstanceId,level:EnchantmentLevel)=>boolean; }

/** Deterministic, guaranteed enchantment transaction. Gameplay has no failure roll. */
export class EnchantmentService {
  readonly #inventory:InventoryManager;readonly #currency:CurrencyService;readonly #walletId:WalletId;readonly #ownerId:EntityId;readonly #resolveMaterialOwnerId:(itemId:string)=>EntityId;readonly #resolveItemInfo:EnchantmentItemInfoResolver;readonly #canEnchantNow:()=>boolean;readonly #findEquippedEntry:EnchantmentServiceOptions["findEquippedEntry"];readonly #changeEquippedEnchantment:EnchantmentServiceOptions["changeEquippedEnchantment"];readonly #processedTransactions=new Set<string>();
  constructor(options:EnchantmentServiceOptions){this.#inventory=options.inventoryManager;this.#currency=options.currencyService;this.#walletId=options.walletId;this.#ownerId=options.inventoryOwnerId;this.#resolveMaterialOwnerId=options.resolveMaterialOwnerId??(()=>this.#ownerId);this.#resolveItemInfo=options.resolveItemInfo;this.#canEnchantNow=options.canEnchantNow??(()=>true);this.#findEquippedEntry=options.findEquippedEntry;this.#changeEquippedEnchantment=options.changeEquippedEnchantment;}
  preview(instanceId:ItemInstanceId):EnchantmentPreview|undefined{const slot=this.#inventory.findEntryByInstanceId(this.#ownerId,instanceId);const entry=slot?.entry??this.#findEquippedEntry(instanceId);if(!entry)return;const level=getEnchantmentLevel(entry);const info=this.#resolveItemInfo(entry.itemId);const baseRecipe=getNextEnchantmentRecipe(level);const recipe=info===undefined||baseRecipe===undefined?baseRecipe:scaleEnchantmentRecipe(baseRecipe,info.itemTier,info.costCategory,info.craftMaterials);const staticFailure=this.#validateStatic(info,level,recipe);const failureReason=staticFailure??(!this.#canEnchantNow()?"combat_active":undefined);const silver=this.#currency.getBalance(this.#walletId,"currency_silver");const silverBalance=silver.ok?silver.value:0;const materials=(recipe?.materials??[]).map(material=>{const owned=this.#inventory.getTotalQuantity(this.#resolveMaterialOwnerId(material.itemId),material.itemId);return{...material,owned,missing:Math.max(0,material.quantity-owned)};});const silverCost=recipe?.silverCost??0;const preview:EnchantmentPreview={instanceId,itemId:entry.itemId,currentLevel:level,nextLevel:recipe?.toLevel,enabled:recipe?.enabled??false,silverCost,materials,canAfford:failureReason===undefined&&silverBalance>=silverCost&&materials.every(m=>m.missing===0)};return failureReason===undefined?preview:{...preview,failureReason};}
  enchant(instanceId:ItemInstanceId,transactionId:string):EnchantmentResult{if(this.#processedTransactions.has(transactionId))return{ok:false,reason:"transaction_already_processed"};if(!this.#canEnchantNow())return{ok:false,reason:"combat_active"};const slot=this.#inventory.findEntryByInstanceId(this.#ownerId,instanceId);const equippedEntry=this.#findEquippedEntry(instanceId);const entry=slot?.entry??equippedEntry;if(!entry)return{ok:false,reason:"item_not_found"};const level=getEnchantmentLevel(entry);const info=this.#resolveItemInfo(entry.itemId);const baseRecipe=getNextEnchantmentRecipe(level);const recipe=info===undefined||baseRecipe===undefined?baseRecipe:scaleEnchantmentRecipe(baseRecipe,info.itemTier,info.costCategory,info.craftMaterials);const staticFailure=this.#validateStatic(info,level,recipe);if(staticFailure)return{ok:false,reason:staticFailure};if(!recipe)return{ok:false,reason:"maximum_level_reached"};if(slot?.entry!==undefined&&slot.entry.quantity>1&&this.#inventory.findFreeSlots(this.#ownerId).length===0)return{ok:false,reason:"inventory_full"};if(!this.#currency.canSpend(this.#walletId,"currency_silver",recipe.silverCost).ok)return{ok:false,reason:"insufficient_silver"};for(const material of recipe.materials){if(this.#inventory.getTotalQuantity(this.#resolveMaterialOwnerId(material.itemId),material.itemId)<material.quantity)return{ok:false,reason:"insufficient_materials"};}
    let changedInstanceId=instanceId;if(slot?.entry!==undefined){const changed=this.#inventory.changeOneEnchantmentAt(this.#ownerId,slot.position,recipe.toLevel);if(!changed.ok||changed.value.entry===undefined)throw new Error("Prevalidated enchantment commit failed");changedInstanceId=changed.value.entry.instanceId;}else if(!this.#changeEquippedEnchantment(instanceId,recipe.toLevel)){throw new Error("Prevalidated equipped enchantment commit failed");}
    for(const material of recipe.materials){const removed=this.#inventory.removeQuantity(this.#resolveMaterialOwnerId(material.itemId),material.itemId,material.quantity);if(!removed.ok)throw new Error("Prevalidated enchantment material commit failed");}
    const debited=this.#currency.debit(this.#walletId,"currency_silver",recipe.silverCost);if(!debited.ok)throw new Error("Prevalidated enchantment currency commit failed");this.#processedTransactions.add(transactionId);return{ok:true,instanceId:changedInstanceId,fromLevel:level,toLevel:recipe.toLevel};}
  #validateStatic(info:EnchantmentItemInfo|undefined,level:EnchantmentLevel,recipe:EnchantmentRecipe|undefined):EnchantmentFailureReason|undefined{if(info===undefined||!info.enchantable)return"item_not_enchantable";if(level>=info.maximumLevel||recipe===undefined)return"maximum_level_reached";if(!recipe.enabled)return"level_reserved";return undefined;}
}
