import type { EntityId, World } from "@game/core";
import type { InventoryManager } from "../inventory/inventory-manager.js";
import { getEnchantmentLevel, isEnchantmentLevel, type EnchantmentLevel, type InventoryEntry, type ItemInstanceId } from "../inventory/types.js";
import { EquipmentComponent, type EquipmentData } from "./components.js";
import type { EquipmentStatSync } from "./equipment-stat-sync.js";
import { EQUIPMENT_SLOTS, equipmentFail, equipmentOk, type EquipOutcome, type EquipmentInfoLike, type EquipmentInfoResolver, type EquipmentLoadout, type EquipmentLoadoutApplyOutcome, type EquipmentLoadoutSlot, type EquipmentResult, type EquipmentSlot, type UnequipOutcome, type WeaponHandling } from "./types.js";

export type EquipmentMutationGuard = (entityId: EntityId) => boolean;
interface ResolvedLoadoutEntry { readonly slot: EquipmentSlot; readonly entry: InventoryEntry; readonly source: "equipped" | "inventory"; readonly inventoryPosition?: number | undefined; }

export class EquipmentManager {
  readonly #world: World; readonly #inventoryManager: InventoryManager; readonly #resolveEquipmentInfo: EquipmentInfoResolver; readonly #statSync: EquipmentStatSync | undefined; readonly #canMutate: EquipmentMutationGuard | undefined; readonly #equipped = new Set<EntityId>(); readonly #loadouts = new Map<EntityId, Map<string, EquipmentLoadout>>();
  constructor(world: World, inventoryManager: InventoryManager, resolveEquipmentInfo: EquipmentInfoResolver, statSync?: EquipmentStatSync, canMutate?: EquipmentMutationGuard) { this.#world = world; this.#inventoryManager = inventoryManager; this.#resolveEquipmentInfo = resolveEquipmentInfo; this.#statSync = statSync; this.#canMutate = canMutate; }
  get equipmentInfoResolver(): EquipmentInfoResolver { return this.#resolveEquipmentInfo; }
  attachEquipment(entityId: EntityId): void { const data: EquipmentData = { slots: new Map() }; this.#world.addComponent(entityId, EquipmentComponent, data); this.#equipped.add(entityId); this.#loadouts.set(entityId, new Map()); }
  detachEquipment(entityId: EntityId): void { const data = this.#getData(entityId); if (data.slots.size > 0) throw new Error("Cannot detach equipment while items are equipped (no item loss)"); this.#world.removeComponent(entityId, EquipmentComponent); this.#equipped.delete(entityId); this.#loadouts.delete(entityId); }
  hasEquipment(entityId: EntityId): boolean { return this.#world.hasComponent(entityId, EquipmentComponent); }
  listEquippedEntities(): readonly EntityId[] { return [...this.#equipped]; }
  getEquipped(entityId: EntityId): ReadonlyMap<EquipmentSlot, InventoryEntry> { return this.#getData(entityId).slots; }
  getEquippedItem(entityId: EntityId, slot: EquipmentSlot): InventoryEntry | undefined { return this.#getData(entityId).slots.get(slot); }
  getLoadouts(entityId: EntityId): readonly EquipmentLoadout[] { const loadouts = this.#loadouts.get(entityId); if (loadouts === undefined) return []; return [...loadouts.values()].map((loadout) => this.#cloneLoadout(loadout)); }
  saveCurrentLoadout(entityId: EntityId, loadoutId: string, name: string): EquipmentResult<EquipmentLoadout> { if (loadoutId.trim().length === 0 || name.trim().length === 0) return equipmentFail("loadout_invalid"); const data = this.#getData(entityId); const slots: EquipmentLoadoutSlot[] = []; for (const slot of EQUIPMENT_SLOTS) { const entry = data.slots.get(slot); if (entry === undefined) continue; slots.push({ slot, instanceId: entry.instanceId, itemId: entry.itemId, enchantment: getEnchantmentLevel(entry) }); } const loadout: EquipmentLoadout = { id: loadoutId.trim(), name: name.trim(), slots }; this.#getLoadoutMap(entityId).set(loadout.id, loadout); return equipmentOk(this.#cloneLoadout(loadout)); }
  renameLoadout(entityId: EntityId, loadoutId: string, name: string): EquipmentResult<EquipmentLoadout> { const trimmedName = name.trim(); if (trimmedName.length === 0) return equipmentFail("loadout_invalid"); const loadout = this.#loadouts.get(entityId)?.get(loadoutId); if (loadout === undefined) return equipmentFail("loadout_not_found"); const renamed = { ...loadout, name: trimmedName }; this.#getLoadoutMap(entityId).set(loadoutId, renamed); return equipmentOk(this.#cloneLoadout(renamed)); }
  deleteLoadout(entityId: EntityId, loadoutId: string): boolean { return this.#loadouts.get(entityId)?.delete(loadoutId) ?? false; }
  applyLoadout(entityId: EntityId, loadoutId: string, maxTier?: number): EquipmentResult<EquipmentLoadoutApplyOutcome> {
    if (!this.#isMutationAllowed(entityId)) return equipmentFail("equipment_locked"); const loadout = this.#loadouts.get(entityId)?.get(loadoutId); if (loadout === undefined) return equipmentFail("loadout_not_found"); const data = this.#getData(entityId); const targetBySlot = new Map<EquipmentSlot, ResolvedLoadoutEntry>(); const seenInstances = new Set<ItemInstanceId>();
    for (const reference of loadout.slots) { if (targetBySlot.has(reference.slot) || seenInstances.has(reference.instanceId)) return equipmentFail("loadout_invalid"); seenInstances.add(reference.instanceId); const equippedMatch = [...data.slots.entries()].find(([, entry]) => entry.instanceId === reference.instanceId); const inventoryMatch = equippedMatch === undefined ? this.#inventoryManager.findEntryByInstanceId(entityId, reference.instanceId) : undefined; const entry = equippedMatch?.[1] ?? inventoryMatch?.entry; if (entry === undefined) return equipmentFail("loadout_item_missing"); if (entry.itemId !== reference.itemId || getEnchantmentLevel(entry) !== reference.enchantment) return equipmentFail("loadout_invalid"); const info = this.#resolveEquipmentInfo(entry.itemId); if (info === undefined || info.slot !== reference.slot) return equipmentFail("loadout_invalid"); if (maxTier !== undefined && info.tier !== undefined && info.tier > maxTier) return equipmentFail("tier_cap_exceeded"); targetBySlot.set(reference.slot, { slot: reference.slot, entry, source: equippedMatch === undefined ? "inventory" : "equipped", ...(inventoryMatch === undefined ? {} : { inventoryPosition: inventoryMatch.position }) }); }
    const targetWeapon = targetBySlot.get("weapon"); if (targetWeapon !== undefined && this.#resolveEquipmentInfo(targetWeapon.entry.itemId)?.handling === "two_handed" && targetBySlot.has("off_hand")) return equipmentFail("two_handed_conflict");
    const targetInstances = new Set([...targetBySlot.values()].map(({ entry }) => entry.instanceId)); const returningEntries = [...data.slots.values()].filter((entry) => !targetInstances.has(entry.instanceId)); const inventoryTargets = [...targetBySlot.values()].filter((resolved) => resolved.source === "inventory"); const vacatedPositions = new Set(inventoryTargets.flatMap((resolved) => resolved.entry.quantity === 1 && resolved.inventoryPosition !== undefined ? [resolved.inventoryPosition] : [])); const availableDestinations = this.#inventoryManager.findFreeSlots(entityId).length + vacatedPositions.size; if (availableDestinations < returningEntries.length) return equipmentFail("inventory_full");
    const extractedByInstance = new Map<ItemInstanceId, InventoryEntry>(); for (const resolved of inventoryTargets) { const position = resolved.inventoryPosition; if (position === undefined) return equipmentFail("loadout_invalid"); const extracted = this.#inventoryManager.takeOneAt(entityId, position); if (!extracted.ok || extracted.value.instanceId !== resolved.entry.instanceId) throw new Error("Equipment loadout prevalidation drifted during atomic apply"); extractedByInstance.set(extracted.value.instanceId, extracted.value); }
    for (const entry of returningEntries) { const inserted = this.#inventoryManager.insertEntry(entityId, entry, undefined, false); if (!inserted.ok) throw new Error("Equipment loadout capacity prevalidation drifted during atomic apply"); }
    const changedSlots: EquipmentSlot[] = []; for (const slot of EQUIPMENT_SLOTS) { const previous = data.slots.get(slot); const target = targetBySlot.get(slot); const targetEntry = target === undefined ? undefined : extractedByInstance.get(target.entry.instanceId) ?? target.entry; if (previous?.instanceId !== targetEntry?.instanceId) changedSlots.push(slot); }
    data.slots.clear(); for (const [slot, target] of targetBySlot) data.slots.set(slot, extractedByInstance.get(target.entry.instanceId) ?? target.entry); this.syncStats(entityId); return equipmentOk({ loadoutId, changedSlots });
  }
  changeEquippedEnchantment(entityId: EntityId, instanceId: ItemInstanceId, enchantment: EnchantmentLevel): boolean { if (!this.#isMutationAllowed(entityId) || !isEnchantmentLevel(enchantment)) return false; const data = this.#getData(entityId); for (const [slot, entry] of data.slots) { if (entry.instanceId !== instanceId) continue; data.slots.set(slot, { ...entry, enchantment }); this.#refreshLoadoutReference(entityId, instanceId, enchantment); this.syncStats(entityId); return true; } return false; }
  canEquip(entityId: EntityId, itemId: string): EquipmentResult<EquipmentInfoLike> { if (!this.#isMutationAllowed(entityId)) return equipmentFail("equipment_locked"); const info = this.#resolveEquipmentInfo(itemId); if (info === undefined) return equipmentFail("not_equippable"); const data = this.#getData(entityId); if (info.slot === "off_hand" && this.#weaponHandling(data) === "two_handed") return equipmentFail("two_handed_conflict"); return equipmentOk(info); }
  equipFromInventory(entityId: EntityId, position: number): EquipmentResult<EquipOutcome> { if (!this.#isMutationAllowed(entityId)) return equipmentFail("equipment_locked"); const data = this.#getData(entityId); const slotResult = this.#inventoryManager.getSlot(entityId, position); if (!slotResult.ok) return equipmentFail("invalid_position"); const entry = slotResult.value.entry; if (entry === undefined) return equipmentFail("entry_not_found"); const info = this.#resolveEquipmentInfo(entry.itemId); if (info === undefined) return equipmentFail("not_equippable"); const slot = info.slot; if (slot === "off_hand" && this.#weaponHandling(data) === "two_handed") return equipmentFail("two_handed_conflict"); const replaced = data.slots.get(slot); let displacedOffHand: InventoryEntry | undefined; if (slot === "weapon" && info.handling === "two_handed") displacedOffHand = data.slots.get("off_hand"); const returningCount = [replaced, displacedOffHand].filter((returningEntry) => returningEntry !== undefined).length; const sourceVacatesSlot = entry.quantity === 1; const availableDestinations = this.#inventoryManager.findFreeSlots(entityId).length + (sourceVacatesSlot ? 1 : 0); if (availableDestinations < returningCount) return equipmentFail("inventory_full"); const extracted = this.#inventoryManager.takeOneAt(entityId, position); if (!extracted.ok) return equipmentFail(extracted.reason === "invalid_position" ? "invalid_position" : "entry_not_found"); const equippedEntry = extracted.value; data.slots.set(slot, equippedEntry); if (replaced !== undefined) this.#inventoryManager.insertEntry(entityId, replaced, sourceVacatesSlot ? position : undefined, false); if (displacedOffHand !== undefined) { data.slots.delete("off_hand"); this.#inventoryManager.insertEntry(entityId, displacedOffHand, replaced === undefined && sourceVacatesSlot ? position : undefined, false); } this.syncStats(entityId); return equipmentOk({ slot, equipped: equippedEntry, replaced, displacedOffHand }); }
  unequipToInventory(entityId: EntityId, slot: EquipmentSlot): EquipmentResult<UnequipOutcome> { if (!this.#isMutationAllowed(entityId)) return equipmentFail("equipment_locked"); const data = this.#getData(entityId); const entry = data.slots.get(slot); if (entry === undefined) return equipmentFail("slot_empty"); const inserted = this.#inventoryManager.insertEntry(entityId, entry, undefined, false); if (!inserted.ok) return equipmentFail("inventory_full"); data.slots.delete(slot); this.syncStats(entityId); return equipmentOk({ slot, entry, position: inserted.value.position }); }
  syncStats(entityId: EntityId): void { this.#statSync?.apply(entityId, this.#getData(entityId).slots); }
  _restore(entityId: EntityId, data: EquipmentData): void { this.#world.setComponent(entityId, EquipmentComponent, data); this.#equipped.add(entityId); if (!this.#loadouts.has(entityId)) this.#loadouts.set(entityId, new Map()); this.syncStats(entityId); }
  _restoreLoadouts(entityId: EntityId, loadouts: readonly EquipmentLoadout[]): void { this.#loadouts.set(entityId, new Map(loadouts.map((loadout) => [loadout.id, this.#cloneLoadout(loadout)]))); }
  #getData(entityId: EntityId): EquipmentData { return this.#world.getComponent(entityId, EquipmentComponent); }
  #getLoadoutMap(entityId: EntityId): Map<string, EquipmentLoadout> { let loadouts = this.#loadouts.get(entityId); if (loadouts === undefined) { loadouts = new Map(); this.#loadouts.set(entityId, loadouts); } return loadouts; }
  #cloneLoadout(loadout: EquipmentLoadout): EquipmentLoadout { return { id: loadout.id, name: loadout.name, slots: loadout.slots.map((slot) => ({ ...slot })) }; }
  #refreshLoadoutReference(entityId: EntityId, instanceId: ItemInstanceId, enchantment: EnchantmentLevel): void { const loadouts = this.#loadouts.get(entityId); if (loadouts === undefined) return; for (const [id, loadout] of loadouts) { let changed = false; const slots = loadout.slots.map((slot) => { if (slot.instanceId !== instanceId) return slot; changed = true; return { ...slot, enchantment }; }); if (changed) loadouts.set(id, { ...loadout, slots }); } }
  #weaponHandling(data: EquipmentData): WeaponHandling { const weapon = data.slots.get("weapon"); if (weapon === undefined) return "none"; return this.#resolveEquipmentInfo(weapon.itemId)?.handling ?? "none"; }
  #isMutationAllowed(entityId: EntityId): boolean { return this.#canMutate?.(entityId) ?? true; }
}
